/* opxx(a,b) OP##a is the enumerate no of operator b */
opxx(PLUS, " + " ) 
opxx(MINUS, " - ") 
opxx(MULT, " * ") 
opxx(DIV, " / ") 
opxx(MOD, " % ") 
opxx(ASGN," = ")
opxx(EQL," == ")
opxx(LEQ, " <= ") 
opxx(NEQ, " != ")
opxx(LSS, " < ")
opxx(GEQ, " >= ")
opxx(GTR, " > ")
opxx(ODD, "odd ")
